apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-auth-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
type: Opaque
stringData:
  AUTH_DB_PASSWORD: password
  AUTH_DB_HOST: "postgres-auth"
  AUTH_DB_PORT: "5432"
  AUTH_DB_USER: "postgres-auth"
  AUTH_DB_NAME: "auth"
  AUTH_DB_SSLMODE: "disable"
  MIGRATION_PATH: "file:///app/migrations"
  AUTO_MIGRATE: "false" 
{{- if eq .Values.global.env "staging" }}
  ENVIRONMENT: "staging" 
  OTP_LENGTH: "6"
  OTP_EXPIRY: "15" 
  OTP_MAX_ATTEMPTS: "5"
{{- end }}