apiVersion: v1
kind: Service
metadata:
  name: ecommerce-auth-service
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: ecommerce-auth-app
  ports:
    - name: tcp-grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP 