apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ecommerce-auth-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: ecommerce-auth-deployment
  minReplicas: {{ if eq .Values.global.env "dev" }}1{{ else }}2{{ end }}
  maxReplicas: {{ if eq .Values.global.env "dev" }}2{{ else }}4{{ end }}
  targetCPUUtilizationPercentage: 50 # Over 50% use CPU -> Scaling 