apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  labels:
    app: postgres-auth
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres-auth
  type: ClusterIP
  sessionAffinity: None 