global:
  env: "prod"
  namespace: ""
  privateRegistry: ""
  pullSecret: ""
  domain:
    frontend: ""
    backend: ""
    s3: ""
product-service:
  image:
    repository: "product-service"
    tag: "ca352633-v1.3"
  config:
    minioAccessKey: ""
    minioSecretKey: ""
mail-service:
  image:
    repository: "mail-service"
    tag: "5919c246"
  config:
    MAIL_USERNAME: "noreply@vntech.id.vn"
    MAIL_PASSWORD: "Tannghi123@"
rabbitmq:
  commonAnnotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Ignore=true
  auth:
    username: guest
    password: guest
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: "longhorn-storage-retain"
    size: 1Gi
  fullnameOverride: rabbitmq
authentication-service:
  image:
    repository: "authentication-service"
    tag: "d3ebb85f-v1.4"
broker-service:
  image:
    repository: "broker-service"
    tag: "771b2f19"
cart-service:
  image:
    repository: "cart-service"
    tag: "v1"
checkout-service:
  image:
    repository: "checkout-service"
    tag: "45e15473"
frontend:
  image:
    repository: "frontend"
    tag: "10bbc0f4-v1.2-prod"
listener-service:
  image:
    repository: "listener-service"
    tag: "b5044da3"
logger-service:
  image:
    repository: "logger-service"
    tag: "c81b5fe8"
user-service:
  image:
    repository: "user-service"
    tag: "eccd0609"
