global:
  namespace: ""
  imageRegistry: ""
  pullSecret: ""
  domain:
    frontend: ""
    backend: ""
    s3: ""
product-service:
  image:
    repository: "product-service"
    tag: "fdad773f"
  config:
    minioAccessKey: ""
    minioSecretKey: ""
mail-service:
  image:
    repository: "mail-service"
    tag: "f7f31d4e"
  config:
    MAIL_USERNAME: "noreply@vntech.id.vn"
    MAIL_PASSWORD: "Tannghi123@"
authentication-service:
  image:
    repository: "authentication-service"
    tag: "v1"
broker-service:
  image:
    repository: "broker-service"
    tag: "9b509937"
cart-service:
  image:
    repository: "cart-service"
    tag: "v1"
checkout-service:
  image:
    repository: "checkout-service"
    tag: "45e15473"
frontend:
  image:
    repository: "frontend"
    tag: "72553145"
listener-service:
  image:
    repository: "listener-service"
    tag: "196f976a"
logger-service:
  image:
    repository: "logger-service"
    tag: "c81b5fe8"
user-service:
  image:
    repository: "user-service"
    tag: "v1"
