apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-listener-secret
  
type: Opaque
stringData:
  MAIL_SERVICE_HOST: "ecommerce-mail-service:50057"
  LOGGER_SERVICE_HOST: "ecommerce-logger-service:50056"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672" 
  USER_SERVICE_HOST: "ecommerce-user-service:50052"