apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-logger-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  MONGO_HOST: "mongo-logger"
  MONGO_PORT: "27017"
  MONGO_USERNAME: "logger_user"
  MONGO_PASSWORD: "password"
  MONGO_DATABASE: "logs"
  AUTO_MIGRATE: "false" 