apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-logger
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceName: mongo-logger
  replicas: 1
  selector:
    matchLabels:
      app: mongo-logger
  template:
    metadata:
      labels:
        app: mongo-logger
    spec:
      containers:
        - name: mongo-logger
          image: mongo:4.2.16-bionic
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: ecommerce-logger-secret
                  key: MONGO_DATABASE
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-logger-secret
                  key: MONGO_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-logger-secret
                  key: MONGO_PASSWORD
          volumesMounts:
              - name: mongo-logger-data
                mountPath: /data/db
      volumes:
        - name: mongo-checkout-data
          persistentVolumeClaim:
            claimName: mongo-logger-pvc

                  
                  
                  




