apiVersion: v1
kind: Service
metadata:
  name: mongo-logger
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: mongo-logger
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo
  selector:
    app: mongo-logger
  type: ClusterIP
  sessionAffinity: None 