apiVersion: v1
kind: Service
metadata:
  name: postgres-products
  labels:
    app: postgres-products
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres-products
  type: ClusterIP
  sessionAffinity: None 