apiVersion: v1
kind: Service
metadata:
  name: postgres-products
  labels:
    app: postgres-products
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    argocd.argoproj.io/sync-wave: "0"
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres-products
  type: ClusterIP
  sessionAffinity: None 