apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-product-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-product-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
      metadata:
        labels:
          app: ecommerce-product-app
      spec:
        initContainers:
          - name: wait-for-postgres-product-db
            image: busybox:1.28
            command: ['sh', '-c', 'until nslookup postgres-products.ecommerce.svc.cluster.local; do echo waiting for postgres; sleep 2; done;']
        containers:
          - name: ecommerce-product-app
            image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports: 
              - containerPort: 50053
              - containerPort: 8082
                name: tcp
                protocol: TCP
            resources:
              requests:
                cpu: "125m"
                memory: "250Mi"
              limits:
                cpu: "250m"
                memory: "500Mi"
            envFrom:
              - secretRef:
                  name: ecommerce-product-secret
        imagePullSecrets:
          - name: {{ .Values.global.pullSecret }}