apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-product-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "argocd.argoproj.io/sync-wave": "0"
type: Opaque
stringData:
  PRODUCT_DB_PASSWORD: password
  PRODUCT_DB_HOST: "postgres-products"
  PRODUCT_DB_PORT: "5432"
  PRODUCT_DB_USER: "postgres-products"
  PRODUCT_DB_NAME: "products"
  PRODUCT_DB_SSLMODE: "disable"
  MIGRATION_PATH: "file:///app/migrations"
  AUTO_MIGRATE: "false"
  MINIO_ACCESS_KEY_ID: {{ .Values.config.minio-access-key }}
  MINIO_SECRET_ACCESS_KEY: {{ .Values.config.minio-secret-key }}
  STORAGE_PROVIDER: minio
  MINIO_ENDPOINT: {{ .Values.global.domain.s3 }}
  MINIO_USE_SSL: "true"
  MINIO_BUCKET_NAME: images
  MINIO_BASE_URL: https://{{ .Values.global.domain.s3 }}
  MINIO_PRESIGNED_TTL: "3600"
  MINIO_LOCATION: us-east-1