apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend-development
  
spec:
  replicas: {{ if eq .Values.global.env "dev" }}1{{ else }}2{{ end }}
  selector:
    matchLabels:
      app: ecommerce-frontend-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
      metadata:
        labels:
          app: ecommerce-frontend-app
      spec:
        containers:
          - name: ecommerce-frontend
            image: "{{ .Values.global.privateRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports: 
              - containerPort: 80
                name: tcp
                protocol: TCP
            resources:
              requests:
                cpu: "250m"
                memory: "350Mi"
              limits:
                cpu: "250m"
                memory: "750Mi"
        imagePullSecrets:
          - name: {{ .Values.global.pullSecret }}
        

