apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cart
  annotations:
    argocd.argoproj.io/sync-wave: "-2" 
spec:
  selector:
    matchLabels:
      app: redis-cart
  serviceName: "redis-cart"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: redis:7.0
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecommerce-cart-secret
              key: REDIS_PASSWORD
              optional: true
        volumesMounts:
        - name: redis-cart-data
          mountPath: /data
      volumes:
        - name: redis-cart-data
          persistentVolumeClaim:
            claimName: redis-cart-pvc
