apiVersion: v1
kind: Service
metadata:
  name: ecommerce-cart-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: ecommerce-cart-app
  ports:
    - name: tcp-grpc
      protocol: TCP
      port: 50054
      targetPort: 50054
  type: ClusterIP 