apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: redis-cart
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: ClusterIP
  selector:
    app: redis-cart 