apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-service
  
spec:
  selector:
    app: ecommerce-frontend-app
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
