apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-mail-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
type: Opaque
stringData:
  MAIL_DOMAIN: "vntech.id.vn"
  MAIL_HOST: "mail93142.maychuemail.com"
  MAIL_PORT: "587"
  MAIL_ENCRYPTION: "tls"
  MAIL_USERNAME: {{ .Values.config.MAIL_USERNAME }}
  MAIL_PASSWORD: {{ .Values.config.MAIL_PASSWORD }}
  FROM_NAME: "VNTECH E-commerce"
  FROM_ADDR: "noreply@vntech.id.vn"