apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-mail-secret
  
type: Opaque
stringData:
  MAIL_DOMAIN: "vntech.id.vn"
  MAIL_HOST: "mail.vntech.id.vn"
  MAIL_PORT: "587"
  MAIL_ENCRYPTION: "tls"
  MAIL_USERNAME: "noreply@vntech.id.vn"
  MAIL_PASSWORD: "Tannghi123@"
  FROM_NAME: "VNTECH E-commerce"
  FROM_ADDR: "noreply@vntech.id.vn"