apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-checkout-pvc
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Skip
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage-retain
  resources:
    requests:
      storage: 5Gi
