apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-checkout-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-checkout-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
      metadata:
        labels:
          app: ecommerce-checkout-app
      spec:
        initContainers:
          - name: wait-for-postgres-checkout-db
            image: busybox:1.28
            command: ['sh', '-c', 'until nslookup mongo-checkout.{{ .Values.global.namespace }}.svc.cluster.local; do echo waiting for mongo; sleep 2; done;']
        containers:
          - name: ecommerce-checkout-app
            image: "{{ .Values.global.privateRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports: 
              - containerPort: 50055
                name: tcp
                protocol: TCP
            resources:
              requests:
                cpu: "250m"
                memory: "350Mi"
              limits:
                cpu: "250m"
                memory: "750Mi"
            envFrom:
              - secretRef:
                  name: ecommerce-checkout-secret
        imagePullSecrets:
          - name: {{ .Values.global.pullSecret }}
        

