apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-checkout-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  MONGO_HOST: "mongo-checkout"
  MONGO_PORT: "27017"
  MONGO_USERNAME: "checkout_user"
  MONGO_PASSWORD: "password"
  MONGO_DATABASE: "checkout"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  AUTO_MIGRATE: "false" 