apiVersion: v1
kind: Service
metadata:
  name: ecommerce-checkout-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: ecommerce-checkout-app
  ports:
    - name: tcp-grpc
      protocol: TCP
      port: 50055
      targetPort: 50055
  type: ClusterIP 