apiVersion: v1
kind: Service
metadata:
  name: mongo-checkout
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app: mongo-checkout
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo
  selector:
    app: mongo-checkout
  type: ClusterIP
  sessionAffinity: None 