apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-broker-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ if eq .Values.global.env "prod" }}{{ .Values.global.env }}-{{ .Values.global.domain.backend }}{{ else }}{{ .Values.global.domain.backend }}{{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-broker-service
                port:
                  number: 8080

