apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-broker-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.domain.backend }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-broker-service
                port:
                  number: 8080

