apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd  # change if your ArgoCD is in another namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # sync before other apps
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}  # change this to your desired namespace
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 16.0.8
    helm:
      values: |
        auth:
          username: user
          password: pass
        replicaCount: 3
        persistence:
          enabled: true
          storageClass: longhorn-storage-retain
          size: 2Gi
        fullnameOverride: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # optional if the namespace doesn't exist yet
