apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-broker-development
spec:
  replicas: {{ if eq .Values.global.env "dev" }}1{{ else }}2{{ end }}
  selector:
    matchLabels:
      app: ecommerce-broker-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: ecommerce-broker-app
    spec:
      containers:
      - name: ecommerce-broker-app
        image: "{{ .Values.global.privateRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
          name: tcp
          protocol: TCP
        resources:
          requests:
            cpu: "250m"
            memory: "350Mi"
          limits:
            cpu: "250m"
            memory: "750Mi"
        envFrom:
        - configMapRef:
            name: ecommerce-broker-configmap
      imagePullSecrets:
        - name: {{ .Values.global.pullSecret }}


