apiVersion: v1
kind: Service
metadata:
  name: ecommerce-broker-service
spec:
  selector:
    app: ecommerce-broker-app
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
