apiVersion: v1
kind: Service
metadata:
  name: ecommerce-user-service
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  selector:
    app: ecommerce-user-app
  ports:
    - name: tcp-grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP 