apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-user-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  USER_DB_PASSWORD: password
  USER_DB_HOST: "postgres-users"
  USER_DB_PORT: "5432"
  USER_DB_USER: "postgres-users"
  USER_DB_NAME: "users"
  USER_DB_SSLMODE: "disable"
  MIGRATION_PATH: "file:///app/migrations"
  AUTO_MIGRATE: "false" 