apiVersion: v1
kind: Service
metadata:
  name: ecommerce-user-service
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: ecommerce-user-app
  ports:
    - name: tcp-grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP 